name = "Glorpers"
author = "Starr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43ad4f35d99c3a6605fbc67d813ba7a3923048d51137789e49409f0c93760e84"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
