name = "Glorpers"
author = "Starr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac7264601cf804b23a90434e6f179bbdb304893f229fd98fa18ff58cf457d9eb"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
