name = "Glorpers"
author = "Starr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da983717c05ebf5a0a4d5eefa4a6fe1c063892685fce1ee435ff00fa484d83df"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
